config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todolist.urls", namespace="todolist"))
]

todolist/urls.py
from django.urls import path

from todolist import views

urlpatterns = [
    path("", views.TaskListView.as_view(), name="task-list"),
    path("create/", views.TaskCreateView.as_view(), name="task-create"),
    path("<int:pk>/update/", views.TaskUpdateView.as_view(), name="task-update"),
    path("<int:pk>/delete/", views.TaskDeleteView.as_view(), name="task-delete"),
    path("<int:pk>/update-status/", views.update_status_view, name="task-status-update"),

    path("tags/", views.TagListView.as_view(), name="tag-list"),
    path("tags/create/", views.TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", views.TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", views.TagDeleteView.as_view(), name="tag-delete"),
]

app_name = "todolist"

todolist/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=55)

    def __str__(self) -> str:
        return self.name


class Task(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    status = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ("status", "-created_at")

    def __str__(self) -> str:
        return self.content

todolist/forms.py
from django import forms

from todolist.models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = "__all__"
        widgets = {
            "deadline": forms.TextInput(attrs={"type": "datetime-local"}),
            "tags": forms.CheckboxSelectMultiple()
        }

todolist/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views import generic

from todolist.models import Task, Tag
from todolist.forms import TaskForm


class TaskListView(generic.ListView):
    model = Task
    fields = "__all__"
    queryset = Task.objects.prefetch_related("tags")


class TaskCreateView(generic.CreateView):
    form_class = TaskForm
    template_name = "todolist/task_form.html"
    success_url = reverse_lazy("todolist:task-list")


class TaskUpdateView(generic.UpdateView):
    form_class = TaskForm
    queryset = Task.objects.prefetch_related("tags")
    template_name = "todolist/task_form.html"
    success_url = reverse_lazy("todolist:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    fields = "__all__"
    template_name = "todolist/task_confirm_delete.html"
    success_url = reverse_lazy("todolist:task-list")


class TagListView(generic.ListView):
    model = Tag
    fields = "__all__"


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todolist:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todolist:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    fields = "__all__"
    template_name = "todolist/tag_confirm_delete.html"
    success_url = reverse_lazy("todolist:tag-list")


def update_status_view(request, pk):
    task = Task.objects.get(id=pk)
    task.status = not task.status
    task.save()

    return HttpResponseRedirect(reverse("todolist:task-list"))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TodoList</title>
    <link rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
            integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
            crossorigin="anonymous">
</head>
<body>
  <div class="container-fluid">
      <div class="row">
          <div class="col-sm-2" style="padding-top: 20px">
              {% block sidebar %}
                  {% include "includes/sidebar.html" %}
              {% endblock %}
          </div>
          <div class="col-sm-10 ">
              {% block content %}{% endblock %}
          </div>
      </div>
  </div>
</body>
</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todolist:task-list' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todolist:tag-list' %}">Tags</a></li>
</ul>

templates/todolist/tag_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div style="margin: 20px;">
    <h1 style="margin-bottom: 20px;">Are you sure you want to remove the tag <em>{{ tag.name }}</em>?</h1>
    <form action="" method="post" style="display: inline-block;">
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" value="Yes" class="btn btn-danger" style="margin-right: 10px;">
    </form>
    <a href="{% url 'todolist:tag-list' %}" class="btn btn-secondary" style="display: inline-block;">Cancel</a>
  </div>
{% endblock %}

templates/todolist/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todolist/tag_list.html
{% extends "base.html" %}
{% block content %}
  <h1 style="margin-top: 20px; display: inline-block;">Tags</h1>
  <a href="{% url 'todolist:tag-create' %}" style="float: right; margin-top: 20px;" class="btn btn-primary">Add</a>
{% if tag_list %}
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      {% for tag in tag_list %}
        <tr>
          <td>{{ tag.name }}</td>
          <td><a href="{% url 'todolist:tag-update' pk=tag.id %}" class="btn btn-secondary">Update</a></td>
          <td><a href="{% url 'todolist:tag-delete' pk=tag.id %}" class="btn btn-secondary">Delete</a></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% else %}
  <h1>You have no tags!</h1>
{% endif %}
{% endblock %}

templates/todolist/task_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div style="margin: 20px;">
    <h1 style="margin-bottom: 20px;">Are you sure you want to remove the task <em>{{ task.content }}</em>?</h1>
    <form action="" method="post" style="display: inline-block;">
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" value="Yes" class="btn btn-danger" style="margin-right: 10px;">
    </form>
    <a href="{% url 'todolist:task-list' %}" class="btn btn-secondary" style="display: inline-block;">Cancel</a>
  </div>
{% endblock %}

templates/todolist/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todolist/task_list.html
{% extends "base.html" %}

{% block content %}
  <h1 style="padding-top: 20px">
    TODO list
    <a href="{% url 'todolist:task-create' %}" style="float: right" class="btn btn-primary">
      Add task
    </a>
  </h1>
{% if task_list %}
  {% for task in task_list %}
      <li class="card mb-3">
          <div class="card-body">
            <h5 class="card-title">
              <b>{{ task.content }}
                {% if task.status %}
                  <span style="color: green;">Done</span>
                {% else %} <span style="color: red;">Not done</span>
                {% endif %}
              </b>
            </h5>
              <p class="card-text" style="color:#666666">
                Created: {{ task.created_at }}
                Deadline: {% if task.deadline %} {{ task.deadline }} {% endif %}
              </p>
              <p class="card-text" style="color:#999999">
                Tags: {{ task.tags.all|join:", " }}
                <a href="{% url 'todolist:task-update' pk=task.id %}">Update</a>
                <a href="{% url 'todolist:task-delete' pk=task.id %}">Delete</a>
                {% if task.status %}
                  <a href="{% url 'todolist:task-status-update' pk=task.id %}" class="btn btn-secondary float-right">Undo</a>
                {% else %}
                  <a href="{% url 'todolist:task-status-update' pk=task.id %}" class="btn btn-success float-right">Complete</a>
                {% endif %}
              </p>
          </div>
      </li>
  {% endfor %}
{% endif %}
{% endblock %}